blog/urls.py
from django.urls import path, include

from .views import post_list, post_detail,category_detail,search,new_post, \
    post_list_admin, edit_post, delete_post, new_category,list_category,main

urlpatterns=[
    path('results/',search,name='search'),
    path('post-detail/<slug:slug>/',post_detail,name='post_detail'),
    path('category-detail/<slug:slug>/',category_detail,name='category_detail'),
    #custom admin
    path('new-post/',new_post,name='new_post'),
    path('post-list/',post_list_admin,name='post_list_admin'),
    path('edit-post/<int:pk>/',edit_post,name='edit_post'),
    path('delete-post/<int:pk>/',delete_post,name='delete_post'),
    path('dashboard/',main,name='dashboard'),
    path('list-category/',list_category,name='list_category'),
    path('new-category/',new_category,name='new_category'),
]

selfstudy/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from home import views
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.conf import settings
from account.views import (login_view,register_view,logout_view)
from blog.views import post_list
from django.views.generic import TemplateView
from django.conf.urls import url
from home.sitemaps import PostSitemap, StaticViewSitemap


sitemaps = {
    'posts': PostSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('',post_list,name='home'),
    path('contact/',views.contact,name='contact'),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('login/', login_view, name='login'),
    path('logout/',logout_view,name='logout'),
    path('register/',register_view,name='register'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('robots.txt', TemplateView.as_view(template_name="pages/robots.txt", content_type='text/plain')),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps}),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

    
handler404 = 'home.views.error404'
handler500 = 'home.views.error500'

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from blog.models import Post, Category
from django.db.models import Count
from django.db.models import Max
from django.core.mail import send_mail
from selfstudy.settings import EMAIL_HOST_USER
from django.contrib import messages
import re, sys

TAG_RE = re.compile(r'<[^>]+>')

# Create your views here.
def contact(request):
    template = 'pages/contact.html'

    # import sliderbar of data
    category=Category.objects.annotate(posts_count = Count('post'))
    category_count =round(Category.objects.count()/2)
    posts= Post.objects.all()
    max_view = posts.aggregate(Max('views'))
    post = Post.objects.filter(status='Published').order_by("-published")[:5]
    post_new = Post.objects.filter(status='Published').order_by("-published")[:5]
    
    if request.method == 'POST':
        email = request.POST['email']
        noidung = request.POST['noidung']
        subject = 'Hãy hỗ trợ tôi theo địa chỉ email:  ' + str(email)
        
        message = remove_tags(str(noidung))

        send_mail(subject, 
            message, EMAIL_HOST_USER, ['huuha84@gmail.com'], fail_silently = False)
        messages.info(request,'Liên hệ đã gửi thành công!')
        return redirect('contact')
        
    context={
        'category':category,
        'category_count':category_count,
        'post':post,
        'max_view':max_view,
        'post_new':post_new
    }
    return render(request,template,context)

def error404(request,exception):
    return render(request,'pages/error.html')
    
def error500(request):
    return render(request,'pages/error.html')

def remove_tags(text):
    return TAG_RE.sub('', text)

home/templates/include/calendar.html
<div class="main">
    <div class="sideb">
        <div class="header d-flex justify-content-center">
            <span>
                <span class="month"></span>
                <span class="year"></span>
            </span>
        </div>
        <div class="calender">
            <table>
                <thead>
                    <tr class="weedays">
                        <th data-weekday="sun" data-column="0">Sun</th>
                        <th data-weekday="mon" data-column="1">Mon</th>
                        <th data-weekday="tue" data-column="2">Tue</th>
                        <th data-weekday="wed" data-column="3">Wed</th>
                        <th data-weekday="thu" data-column="4">Thu</th>
                        <th data-weekday="fri" data-column="5">Fri</th>
                        <th data-weekday="sat" data-column="6">Sat</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="days" data-row="0">
                        <td data-column="0"></td>
                        <td data-column="1"></td>
                        <td data-column="2"></td>
                        <td data-column="3"></td>
                        <td data-column="4"></td>
                        <td data-column="5"></td>
                        <td data-column="6"></td>
                    </tr>
                    <tr class="days" data-row="1">
                        <td data-column="0"></td>
                        <td data-column="1"></td>
                        <td data-column="2"></td>
                        <td data-column="3"></td>
                        <td data-column="4"></td>
                        <td data-column="5"></td>
                        <td data-column="6"></td>
                    </tr>
                    <tr class="days" data-row="2">
                        <td data-column="0"></td>
                        <td data-column="1"></td>
                        <td data-column="2"></td>
                        <td data-column="3"></td>
                        <td data-column="4"></td>
                        <td data-column="5"></td>
                        <td data-column="6"></td>
                    </tr>
                    <tr class="days" data-row="3">
                        <td data-column="0"></td>
                        <td data-column="1"></td>
                        <td data-column="2"></td>
                        <td data-column="3"></td>
                        <td data-column="4"></td>
                        <td data-column="5"></td>
                        <td data-column="6"></td>
                    </tr>
                    <tr class="days" data-row="4">
                        <td data-column="0"></td>
                        <td data-column="1"></td>
                        <td data-column="2"></td>
                        <td data-column="3"></td>
                        <td data-column="4"></td>
                        <td data-column="5"></td>
                        <td data-column="6"></td>
                    </tr>
                    <tr class="days" data-row="5">
                        <td data-column="0"></td>
                        <td data-column="1"></td>
                        <td data-column="2"></td>
                        <td data-column="3"></td>
                        <td data-column="4"></td>
                        <td data-column="5"></td>
                        <td data-column="6"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

home/templates/include/header_image.html
{% load static%}
{% load fontawesome %}

<div class="row" style="margin-top:50px;margin-bottom:4px ">

    <div class="col-lg-12">
        <div id="Carousel" class="carousel slide p-0">
            <!-- Carousel items -->
            <div class="carousel-inner">
                <div class="item active carousel-item">
                    <div class="row">
                        <div class="col-md-12">
                            <a href="#"><img src="{% static 'images/pic_01.jpeg'%}" class="img-responsive" width="1112"></a>
                        </div>
                    </div>
                    <!--.row-->
                </div>
                <!--.item-->
                <div class="item carousel-item">
                    <div class="row">
                        <div class="col-md-12">
                            <a href="#"><img src="{% static 'images/pic_02.jpeg'%}" class="img-responsive" width="1112"></a>
                        </div>
                    </div>
                      <!--.row-->
                </div>
                    <!--.item-->
                <div class="item carousel-item">
                    <div class="row">
                        <div class="col-md-12">
                            <a href="#"><img src="{% static 'images/pic_03.jpeg'%}" class="img-responsive" width="1112"></a>
                        </div>
                    </div>
                      <!--.row-->
                </div>
                    <!--.item-->
                <div class="item carousel-item">
                    <div class="row">
                        <div class="col-md-12">
                            <a href="#"><img src="{% static 'images/pic_04.jpeg'%}" class="img-responsive" width="1112"></a>
                        </div>
                    </div>
                          <!--.row-->
                </div>
                <div class="item carousel-item">
                    <div class="row">
                        <div class="col-md-12">
                            <a href="#"><img src="{% static 'images/pic_05.jpeg'%}" class="img-responsive" width="1112"></a>
                        </div>
                    </div>
                      <!--.row-->
                </div>
            </div>
            <!--.carousel-inner-->
            <a class="carousel-control-prev" href="#Carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#Carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <!--.Carousel-->
    </div>
</div>

home/templates/include/pagination.html
{% if items.has_other_pages %}
<div class="text-center">
    <div class="col-6 offset-3 text-center pagination-set">
        <nav aria-label="">
            <ul class="pagination">
            {% if items.has_previous %}
                <li class="page-item"><a class="page-link" tabindex="-1" href="?page={{items.previous_page_number}}{% if query %}&q={{query}}{% endif %}">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" tabindex="-1" href="">&laquo;</a></li>
            {% endif %}

            {% for i in page_range %}
                {% if items.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{i}}<span class="sr-only">(current)</span></a>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{i}}{% if query %}&q={{query}}{% endif %}">{{i}}</a></li>
                {% endif %}
            {% endfor %}

            {% if items.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{items.next_page_number}}{% if query %}&q={{query}}{% endif %}">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
            {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endif %}

home/templates/include/search.html
{% load fontawesome %}

<form class="form-inline my-2 my-md-0" method="GET" action="{% url 'blog:search' %}">
    <input class="form-control mr-sm-2" type="text" name="q" value="{{request.GET.q}}" placeholder="Tìm kiếm...">
    <button class="btn bg-success search-butn my-2 my-sm-0" type="submit">{% fontawesome_icon 'search' color="white"%}</button>
</form>

home/templates/include/sigin.html
{% load fontawesome %}
{% if not request.user.is_authenticated %}
    <p>Ban chua dang nhap vao tai khoan!</p>
    <a class="btn-sm btn-primary text-decoration-none" href="{% url 'register' %}">{% fontawesome_icon 'user-plus' large=True %} Đăng ký</a>
    <a class="btn-sm btn-primary text-decoration-none" href="{% url 'login' %}">{% fontawesome_icon 'sign-in' large=True %} Đăng nhập</a>
{% else %}
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="{{user.profile.image.url}}" class="card-img img-responsive" width="100%" height="100%">
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <p class="card-text">Xin chào {{user.username}}</p>
                    <a class="btn-sm btn-primary text-decoration-none" href="{% url 'logout' %}">{% fontawesome_icon 'sign-out' large=True %} Thoát</a>
                    {% if request.user.is_superuser %}
                    <a class="btn-sm btn-primary text-decoration-none" href="{% url 'blog:dashboard' %}"><i class="fa fa-tachometer"></i> Quản trị bài viết</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endif %}

home/templates/include/slidebar.html
{% load static%}
{% load fontawesome %}

<div class="col-md-4">
    <!-- Gioi thieu -->
    <div class="card my-4  shadow-sm" style="background-image: url({% static 'images/background_logo.jpg'%});height:170px;background-position: center;background-repeat: no-repeat;background-size: cover;">
        <div class="card-body bg-img-body d-flex justify-content-start">
            <img src="{% static 'images/logo_web.svg'%}" class="img-responsive" style="max-width:100%;">   
            <div>
                <p class="icon-traffic num1"><i class="fa fa-line-chart" style="font-size:18px;color:#0753bc"></i><span class="font-weight-bold bg-secondary text-white" style="margin-left: 10px;"> 0000{{max_view.views__max}} </span></p> 
                <p class="icon-traffic"><i class="fa fa-thumbs-up" style="font-size:18px;color:#0753bc"></i><span class="font-weight-bold bg-secondary text-white" style="margin-left: 10px;"> 0000{{max_view.views__max}} </span></p>
            </div>
        </div>
        <div class="d-flex bd-highlight mb-3 btn-end">
            <div class="bd-highlight m-2"><iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fselfstudy.tk%2Fdocs%2Fplugins%2F&layout=button_count&size=large&width=134&height=28&appId" width="134" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe></div>
            <div class="ml-auto m-2 bd-highlight"><a style="font-size:12px"class="btn btn-secondary" href="https://www.w3schools.com/icons/fontawesome_icons_webapp.asp"><i class="fa fa-heart"></i> Liên kết hay</a></div>
        </div>
    </div>

    <!-- Search Widget -->
    <div class="card my-4 shadow-sm">
        {% include 'include/calendar.html'%}
    </div>

    <!-- Categories Widget -->
    <div class="card my-4 shadow-sm">
        <h5 class="card-header">Chuyên mục</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% for obj in category %}
                        <li>
                            <a href="{% url 'blog:category_detail' slug=obj.slug%}">{{obj}}</a>  
                            <span class="badge badge-success">{{obj.posts_count}}</span> 
                        </li>
                        {% if forloop.counter|divisibleby:category_count and not forloop.first %}
                    </ul>
                </div>
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        {% endif %}
                        <li>
                            {% if forloop.last %}  
                        </li> 
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                
            </div>
        </div>
    </div>

    <!-- Side Widget -->
    <div class="card my-4 shadow-sm">
        <h5 class="card-header">Bài viết mới</h5>
        <div class="card-body p-0">
            <ul class="list-unstyled mb-0 p-0">
                {% for obj in post %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'blog:post_detail' slug=obj.slug%}">{% fontawesome_icon 'chevron-circle-right'%} {{obj.title}}</a> 
                </li>
                {% endfor %}  
            </ul>
        </div>
    </div>
    <!--Slide Advertisment-->
    <div class="card my-4 shadow-sm">
        <img src="{% static 'images/quangcao-01.gif'%}" style="max-width: 100%;">
    </div>
    <!-- Side Widget -->

    <div class="card my-4 shadow-sm">
        <h5 class="card-header">Liên kết</h5>
        <div class="card-body">
            <ul class="list-unstyled mb-0" style="margin-left: 40px ">
                <li>
                    <a href="">{% fontawesome_icon 'facebook-square' large=True%} Facebook</a>
                </li>
                <li>
                    <a href="">{% fontawesome_icon 'youtube-square' large=True%} Youtube</a>
                </li>
                <li>
                    <a href="">{% fontawesome_icon 'twitter-square' large=True%} Twister</a>
                </li>
                <li>
                    <a href="">{% fontawesome_icon 'github' large=True%} Github</a>
                </li>
            </ul>
        </div>
    </div>
</div>